# Generated by Django 4.2.30 on 2026-08-18 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchasing', '0003_alter_supplier_organization'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaserecord',
            name='item_name_normalized',
            field=models.CharField(blank=True, db_index=True, max_length=150),
        ),
        migrations.AddIndex(
            model_name='purchaserecord',
            index=models.Index(fields=['branch', 'supplier', 'item_name_normalized'], name='purchasing__branch__479976_idx'),
        ),
    ]
