# Generated by Django 4.2.30 on 2026-08-20 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchasing', '0005_backfill_item_name_normalized'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='bank_account_furigana',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
