# Generated by Django 4.2.30 on 2026-09-17 14:38

from django.db import migrations, models
import django.db.models.deletion
import datetime


def migrate_legacy_payable_overrides(apps, schema_editor):
    Supplier = apps.get_model('purchasing', 'Supplier')
    Override = apps.get_model('purchasing', 'SupplierMonthlyPayableOverride')
    Branch = apps.get_model('branches', 'Branch')
    month = datetime.date(2026, 9, 1)
    rows = []
    for supplier in Supplier.objects.exclude(payable_override=None).iterator():
        for branch_id in Branch.objects.filter(
            organization_id=supplier.organization_id,
        ).values_list('id', flat=True):
            rows.append(Override(
                supplier_id=supplier.id,
                branch_id=branch_id,
                month=month,
                amount=supplier.payable_override,
            ))
    Override.objects.bulk_create(rows, ignore_conflicts=True)


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0003_alter_branch_organization_and_code'),
        ('purchasing', '0007_split_bank_account_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='SupplierMonthlyPayableOverride',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.DateField()),
                ('amount', models.DecimalField(decimal_places=0, max_digits=12)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='branches.branch')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monthly_payable_overrides', to='purchasing.supplier')),
            ],
        ),
        migrations.CreateModel(
            name='PurchaseItemSeed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=150)),
                ('item_name_normalized', models.CharField(max_length=150)),
                ('last_unit_price', models.DecimalField(decimal_places=0, default=0, max_digits=12)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchase_item_seeds', to='branches.branch')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='purchasing.supplier')),
            ],
        ),
        migrations.AddConstraint(
            model_name='suppliermonthlypayableoverride',
            constraint=models.UniqueConstraint(fields=('supplier', 'branch', 'month'), name='unique_supplier_branch_month_payable_override'),
        ),
        migrations.AddConstraint(
            model_name='purchaseitemseed',
            constraint=models.UniqueConstraint(fields=('branch', 'supplier', 'item_name_normalized'), name='unique_purchase_item_seed'),
        ),
        migrations.RunPython(migrate_legacy_payable_overrides, migrations.RunPython.noop),
    ]
