# Generated by Django 4.2.30 on 2026-08-16 15:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('staff', '0001_initial'),
        ('branches', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyReportHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('saved_at', models.DateTimeField(auto_now_add=True)),
                ('edited_by_name', models.CharField(blank=True, max_length=150)),
                ('total_revenue', models.DecimalField(decimal_places=0, default=0, max_digits=12)),
                ('cash_remaining', models.DecimalField(decimal_places=0, default=0, max_digits=12)),
                ('data', models.JSONField()),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_report_history', to='branches.branch')),
                ('edited_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('person_in_charge', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='staff.staffmember')),
            ],
            options={
                'verbose_name_plural': 'daily report history',
                'ordering': ['-saved_at'],
            },
        ),
        migrations.CreateModel(
            name='DailyReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('total_revenue', models.DecimalField(decimal_places=0, default=0, max_digits=12)),
                ('total_customers', models.PositiveIntegerField(default=0)),
                ('group_count', models.PositiveIntegerField(default=0)),
                ('morning_revenue', models.DecimalField(decimal_places=0, default=0, max_digits=12)),
                ('morning_customers', models.PositiveIntegerField(default=0)),
                ('morning_group_count', models.PositiveIntegerField(default=0)),
                ('payment_amounts', models.JSONField(blank=True, default=dict)),
                ('expenses', models.JSONField(blank=True, default=list)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_reports', to='branches.branch')),
                ('person_in_charge', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='staff.staffmember')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.AddConstraint(
            model_name='dailyreport',
            constraint=models.UniqueConstraint(fields=('branch', 'date'), name='unique_daily_report_per_branch_date'),
        ),
    ]
