# Generated by Django 4.2 on 2026-08-30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dailyreports', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyreport',
            name='cash_register_counts',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
