# Generated by Django 4.2.30 on 2026-09-14 15:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0003_alter_branch_organization_and_code'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dailyreports', '0002_dailyreport_cash_register_counts'),
    ]

    operations = [
        migrations.CreateModel(
            name='CashRegisterDefaults',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('denomination_defaults', models.JSONField(blank=True, default=dict)),
                ('expected_total', models.PositiveIntegerField(default=130000)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('branch', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cash_register_defaults', to='branches.branch')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
