# Generated by Django 4.2.30 on 2026-08-17 14:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('staff', '0002_add_employment_fields'),
        ('branches', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SchedulePeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(help_text='A period defaults to Monday-Sunday but any range is allowed, including ones that cross a month boundary.')),
                ('end_date', models.DateField()),
                ('status', models.CharField(choices=[('collecting', 'Collecting availability'), ('drafting', 'Drafting shifts'), ('published', 'Published'), ('closed', 'Closed')], default='collecting', max_length=12)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedule_periods', to='branches.branch')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('published_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-start_date', 'branch_id'],
            },
        ),
        migrations.CreateModel(
            name='Shift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work_date', models.DateField()),
                ('planned_start', models.TimeField()),
                ('planned_end', models.TimeField()),
                ('crosses_midnight', models.BooleanField(default=False)),
                ('planned_break_minutes', models.PositiveIntegerField(default=0)),
                ('position', models.CharField(blank=True, max_length=100)),
                ('note', models.CharField(blank=True, max_length=255)),
                ('override', models.BooleanField(default=False)),
                ('override_reason', models.CharField(blank=True, max_length=255)),
                ('override_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shifts', to='branches.branch')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shifts', to='staff.staffmember')),
                ('override_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shifts', to='scheduling.scheduleperiod')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['work_date', 'branch_id', 'planned_start'],
            },
        ),
        migrations.CreateModel(
            name='AvailabilityRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work_date', models.DateField()),
                ('availability', models.CharField(choices=[('available', 'Available'), ('day_off', 'Day off requested')], max_length=10)),
                ('start_time', models.TimeField(blank=True, null=True)),
                ('end_time', models.TimeField(blank=True, null=True)),
                ('crosses_midnight', models.BooleanField(default=False)),
                ('note', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availability_requests', to='staff.staffmember')),
                ('period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availability_requests', to='scheduling.scheduleperiod')),
            ],
            options={
                'ordering': ['period_id', 'employee_id', 'work_date'],
            },
        ),
        migrations.CreateModel(
            name='ActualWorkRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work_date', models.DateField()),
                ('actual_start', models.TimeField(blank=True, null=True)),
                ('actual_end', models.TimeField(blank=True, null=True)),
                ('crosses_midnight', models.BooleanField(default=False)),
                ('actual_break_minutes', models.PositiveIntegerField(default=0)),
                ('absent', models.BooleanField(default=False)),
                ('statutory_holiday', models.BooleanField(default=False)),
                ('adjustment_reason', models.CharField(blank=True, help_text='Required whenever actual times differ from the shift they were generated from.', max_length=255)),
                ('status', models.CharField(choices=[('pending', 'Pending manager confirmation'), ('manager_confirmed', 'Confirmed by branch manager'), ('admin_locked', 'Locked by admin')], default='pending', max_length=20)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actual_work_records', to='branches.branch')),
                ('confirmed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actual_work_records', to='staff.staffmember')),
                ('shift', models.ForeignKey(blank=True, help_text='Null for an attendance that was never scheduled (walk-in temp coverage, etc).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='actual_work_records', to='scheduling.shift')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['work_date', 'branch_id', 'employee_id'],
            },
        ),
        migrations.AddConstraint(
            model_name='availabilityrequest',
            constraint=models.UniqueConstraint(fields=('period', 'employee', 'work_date'), name='unique_availability_per_period_employee_date'),
        ),
        migrations.AddConstraint(
            model_name='actualworkrecord',
            constraint=models.UniqueConstraint(fields=('employee', 'work_date'), name='unique_actual_work_per_employee_date'),
        ),
    ]
