# Generated by Django 4.2.30 on 2026-08-18 12:37

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0003_alter_branch_organization_and_code'),
        ('scheduling', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BranchScheduleSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('morning_start', models.TimeField(default=datetime.time(10, 30))),
                ('morning_end', models.TimeField(default=datetime.time(15, 0))),
                ('afternoon_start', models.TimeField(default=datetime.time(17, 0))),
                ('afternoon_end', models.TimeField(default=datetime.time(22, 0))),
                ('full_day_start', models.TimeField(default=datetime.time(10, 30))),
                ('full_day_end', models.TimeField(default=datetime.time(22, 0))),
                ('full_day_break_start', models.TimeField(default=datetime.time(15, 0))),
                ('full_day_break_end', models.TimeField(default=datetime.time(17, 0))),
                ('active', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('branch', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='schedule_setting', to='branches.branch')),
            ],
        ),
    ]
