# Generated by Django 4.2.30 on 2026-08-18 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0003_backfill_branch_schedule_settings'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduleperiod',
            name='month',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='scheduleperiod',
            name='start_date',
            field=models.DateField(help_text='Server-computed from `month` for current periods; a legacy period may have any arbitrary range, including ones crossing month bounds.'),
        ),
        migrations.AddConstraint(
            model_name='scheduleperiod',
            constraint=models.UniqueConstraint(condition=models.Q(('month__isnull', False)), fields=('branch', 'month'), name='unique_schedule_period_per_branch_month'),
        ),
    ]
