# Generated by Django 4.2.30 on 2026-08-18 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0004_scheduleperiod_month_alter_scheduleperiod_start_date_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='scheduleperiod',
            name='unique_schedule_period_per_branch_month',
        ),
    ]
