# Generated by Django 4.2.30 on 2026-08-19 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0005_remove_scheduleperiod_unique_schedule_period_per_branch_month'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='scheduleperiod',
            constraint=models.UniqueConstraint(fields=('branch', 'month'), name='unique_schedule_period_per_branch_month'),
        ),
    ]
