# Generated by Django 4.2.30 on 2026-08-16 15:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('branches', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentMethodDef',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField()),
                ('custom_name', models.CharField(blank=True, max_length=100)),
                ('i18n_key', models.CharField(blank=True, max_length=100)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('protected', models.BooleanField(default=False)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_methods', to='branches.branch')),
            ],
            options={
                'ordering': ['branch_id', 'sort_order', 'code'],
            },
        ),
        migrations.AddConstraint(
            model_name='paymentmethoddef',
            constraint=models.UniqueConstraint(fields=('branch', 'code'), name='unique_payment_method_code_per_branch'),
        ),
    ]
