# Generated by Django 4.2.30 on 2026-09-19 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paymentmethods', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentmethoddef',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
