# Generated by Django 4.2.30 on 2026-08-17 14:08

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('staff', '0002_add_employment_fields'),
        ('scheduling', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('branches', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WageRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('effective_from', models.DateField()),
                ('effective_to', models.DateField(blank=True, help_text='Null means still in effect.', null=True)),
                ('hourly_rate', models.DecimalField(decimal_places=0, max_digits=10)),
                ('night_premium_rate', models.DecimalField(decimal_places=4, default=Decimal('0.25'), max_digits=5)),
                ('overtime_premium_rate', models.DecimalField(decimal_places=4, default=Decimal('0.25'), max_digits=5)),
                ('statutory_holiday_premium_rate', models.DecimalField(decimal_places=4, default=Decimal('0.35'), max_digits=5)),
                ('transportation_type', models.CharField(choices=[('none', 'None'), ('per_attendance', 'Per attendance day'), ('monthly', 'Fixed monthly amount')], default='none', max_length=20)),
                ('transportation_amount', models.DecimalField(decimal_places=0, default=0, max_digits=10)),
                ('note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wage_rules', to='staff.staffmember')),
            ],
            options={
                'ordering': ['employee_id', '-effective_from'],
            },
        ),
        migrations.CreateModel(
            name='WageMonthlyClosing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.DateField(help_text='Always stored as the 1st of the target month.')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('confirmed', 'Confirmed'), ('locked', 'Locked')], default='draft', max_length=10)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('locked_at', models.DateTimeField(blank=True, null=True)),
                ('unlocked_at', models.DateTimeField(blank=True, null=True)),
                ('unlock_reason', models.TextField(blank=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wage_monthly_closings', to='branches.branch')),
                ('confirmed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('locked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('unlocked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-month', 'branch_id'],
            },
        ),
        migrations.CreateModel(
            name='WageEmployeeResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employment_type', models.CharField(help_text='Snapshot of the employee type at generation time.', max_length=20)),
                ('attendance_days', models.PositiveIntegerField(default=0)),
                ('total_minutes', models.PositiveIntegerField(default=0)),
                ('regular_minutes', models.PositiveIntegerField(default=0)),
                ('night_minutes', models.PositiveIntegerField(default=0)),
                ('overtime_minutes', models.PositiveIntegerField(default=0)),
                ('statutory_holiday_minutes', models.PositiveIntegerField(default=0)),
                ('base_amount', models.DecimalField(decimal_places=0, default=0, max_digits=12)),
                ('night_premium', models.DecimalField(decimal_places=0, default=0, max_digits=12)),
                ('overtime_premium', models.DecimalField(decimal_places=0, default=0, max_digits=12)),
                ('holiday_premium', models.DecimalField(decimal_places=0, default=0, max_digits=12)),
                ('transportation_amount', models.DecimalField(decimal_places=0, default=0, max_digits=12)),
                ('manual_addition', models.DecimalField(decimal_places=0, default=0, max_digits=12)),
                ('manual_deduction', models.DecimalField(decimal_places=0, default=0, max_digits=12)),
                ('adjustment_reason', models.TextField(blank=True)),
                ('estimated_total', models.DecimalField(decimal_places=0, default=0, max_digits=12)),
                ('wage_rule_snapshot', models.JSONField(blank=True, default=dict)),
                ('calculation_version', models.CharField(default='v1', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('closing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee_results', to='wages.wagemonthlyclosing')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='wage_results', to='staff.staffmember')),
            ],
            options={
                'ordering': ['closing_id', 'employee_id'],
            },
        ),
        migrations.CreateModel(
            name='WageDailyDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work_date', models.DateField()),
                ('total_minutes', models.PositiveIntegerField(default=0)),
                ('regular_minutes', models.PositiveIntegerField(default=0)),
                ('night_minutes', models.PositiveIntegerField(default=0)),
                ('overtime_minutes', models.PositiveIntegerField(default=0)),
                ('statutory_holiday_minutes', models.PositiveIntegerField(default=0)),
                ('base_amount', models.DecimalField(decimal_places=0, default=0, max_digits=12)),
                ('night_premium', models.DecimalField(decimal_places=0, default=0, max_digits=12)),
                ('overtime_premium', models.DecimalField(decimal_places=0, default=0, max_digits=12)),
                ('holiday_premium', models.DecimalField(decimal_places=0, default=0, max_digits=12)),
                ('transportation_amount', models.DecimalField(decimal_places=0, default=0, max_digits=12)),
                ('wage_rule_snapshot', models.JSONField(blank=True, default=dict)),
                ('actual_work_record', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wage_daily_details', to='scheduling.actualworkrecord')),
                ('result', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_details', to='wages.wageemployeeresult')),
                ('wage_rule', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='daily_details', to='wages.wagerule')),
            ],
            options={
                'ordering': ['result_id', 'work_date'],
            },
        ),
        migrations.AddConstraint(
            model_name='wagemonthlyclosing',
            constraint=models.UniqueConstraint(fields=('branch', 'month'), name='unique_wage_closing_per_branch_month'),
        ),
        migrations.AddConstraint(
            model_name='wageemployeeresult',
            constraint=models.UniqueConstraint(fields=('closing', 'employee'), name='unique_wage_result_per_closing_employee'),
        ),
        migrations.AddConstraint(
            model_name='wagedailydetail',
            constraint=models.UniqueConstraint(fields=('result', 'work_date'), name='unique_wage_daily_detail_per_result_date'),
        ),
    ]
