# Generated by Django 4.2.30 on 2026-08-18 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='wagemonthlyclosing',
            name='last_generated_at',
            field=models.DateTimeField(blank=True, help_text='Set every time `generate` successfully (re)computes results. `confirm` refuses to run if this is null (never generated) or older than the newest relevant ActualWorkRecord/WageRule change, so a manager can never confirm stale or empty results without first re-generating.', null=True),
        ),
    ]
