# Generated by Django 4.2.30 on 2026-08-18 13:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('wages', '0002_add_last_generated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='wageemployeeresult',
            name='bonus_amount',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='wageemployeeresult',
            name='bonus_note',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='wageemployeeresult',
            name='bonus_updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='wageemployeeresult',
            name='bonus_updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='wageemployeeresult',
            name='calculation_period_end',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='wageemployeeresult',
            name='calculation_period_start',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='wageemployeeresult',
            name='monthly_transportation_override',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='wageemployeeresult',
            name='transportation_override_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='wageemployeeresult',
            name='transportation_override_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='wageemployeeresult',
            name='transportation_override_reason',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
