# Generated by Django 4.2.30 on 2026-08-18 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wages', '0003_wageemployeeresult_bonus_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='wageemployeeresult',
            name='rule_transportation_amount',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=12),
        ),
    ]
