# Generated by Django 4.2.30 on 2026-09-03 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0002_backfill_default_organization'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='logo_url',
            field=models.URLField(blank=True, default=''),
        ),
    ]
