# Generated by Django 4.2.30 on 2026-09-07 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0004_organizationfeature_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='logo_url',
            field=models.TextField(blank=True, default=''),
        ),
    ]
