# Generated by Django 4.2.30 on 2026-09-14 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0005_alter_organization_logo_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='report_unlock_password_hash',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
    ]
