# Generated by Django 4.2.30 on 2026-08-31 13:11

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('branches', '0003_alter_branch_organization_and_code'),
        ('organizations', '0002_backfill_default_organization'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('paused', 'Paused'), ('ended', 'Ended')], default='draft', max_length=10)),
                ('starts_at', models.DateTimeField(blank=True, null=True)),
                ('ends_at', models.DateTimeField(blank=True, null=True)),
                ('points_per_1000yen', models.PositiveIntegerField(default=10)),
                ('points_per_draw', models.PositiveIntegerField(default=100)),
                ('points_per_voucher', models.PositiveIntegerField(default=100)),
                ('voucher_yen_per_unit', models.PositiveIntegerField(default=100)),
                ('points_expire_months', models.PositiveIntegerField(default=12)),
                ('direct_draw_threshold_yen', models.PositiveIntegerField(blank=True, null=True)),
                ('max_draws_per_verification', models.PositiveIntegerField(default=1)),
                ('max_draws_per_customer_per_day', models.PositiveIntegerField(default=10)),
                ('stamp_target', models.PositiveIntegerField(blank=True, null=True)),
                ('business_day_cutover', models.TimeField(default=datetime.time(5, 0))),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promo_campaigns', to='branches.branch')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='CheckInRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_deleted', models.BooleanField(default=False)),
                ('checked_in_at', models.DateTimeField()),
                ('local_date', models.DateField(help_text='Business day, per Campaign.business_day_cutover.')),
                ('result', models.CharField(default='ok', max_length=16)),
                ('risk_level', models.CharField(default='normal', max_length=16)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promo_checkins', to='branches.branch')),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='checkins', to='promotions.campaign')),
            ],
            options={
                'ordering': ['-checked_in_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=20)),
                ('name', models.CharField(blank=True, max_length=80)),
                ('birthday_md', models.CharField(blank=True, max_length=5)),
                ('card_token', models.CharField(max_length=64, unique=True)),
                ('points_balance', models.IntegerField(default=0)),
                ('stamp_count', models.PositiveIntegerField(default=0)),
                ('first_seen_at', models.DateTimeField(auto_now_add=True)),
                ('last_seen_at', models.DateTimeField(blank=True, null=True)),
                ('last_activity_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('blocked', 'Blocked')], default='active', max_length=10)),
                ('risk_level', models.CharField(default='normal', max_length=16)),
                ('privacy_consented_at', models.DateTimeField(blank=True, null=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='promo_customers', to='organizations.organization')),
                ('registered_campaign', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='promotions.campaign')),
            ],
            options={
                'ordering': ['-last_seen_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='SpendVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_deleted', models.BooleanField(default=False)),
                ('table_number', models.CharField(blank=True, max_length=16)),
                ('amount_yen', models.PositiveIntegerField()),
                ('consumed_at', models.DateTimeField()),
                ('points_granted', models.IntegerField(default=0)),
                ('direct_draws_granted', models.PositiveIntegerField(default=0)),
                ('verified_at', models.DateTimeField(auto_now_add=True)),
                ('source_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('status', models.CharField(choices=[('accepted', 'Accepted'), ('voided', 'Voided')], default='accepted', max_length=10)),
                ('risk_level', models.CharField(default='normal', max_length=16)),
                ('voided_at', models.DateTimeField(blank=True, null=True)),
                ('void_reason', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promo_spend_verifications', to='branches.branch')),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='spend_verifications', to='promotions.campaign')),
                ('check_in_record', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='spend_verifications', to='promotions.checkinrecord')),
                ('customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='spend_verifications', to='promotions.customer')),
                ('verified_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('voided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='PointsLedger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delta', models.IntegerField(help_text='Positive = earned, negative = spent/expired.')),
                ('reason', models.CharField(choices=[('spend', 'Spend'), ('milestone', 'Milestone'), ('draw', 'Lottery draw'), ('voucher', 'Voucher redeem'), ('expire', 'Expiry'), ('adjust', 'Manual adjustment')], max_length=16)),
                ('source_ref', models.CharField(blank=True, max_length=64)),
                ('balance_after', models.IntegerField()),
                ('note', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='points_ledger', to='promotions.customer')),
                ('operator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.AddField(
            model_name='checkinrecord',
            name='customer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='checkins', to='promotions.customer'),
        ),
        migrations.AddField(
            model_name='checkinrecord',
            name='spend_verification',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='promotions.spendverification'),
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['organization', 'phone'], name='promotions__organiz_879616_idx'),
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['organization', 'name'], name='promotions__organiz_53b331_idx'),
        ),
        migrations.AddConstraint(
            model_name='customer',
            constraint=models.UniqueConstraint(fields=('organization', 'phone'), name='unique_promo_customer_phone_per_org'),
        ),
        migrations.AddConstraint(
            model_name='checkinrecord',
            constraint=models.UniqueConstraint(fields=('customer', 'campaign', 'local_date'), name='unique_promo_checkin_per_day'),
        ),
    ]
