# Generated by Django 4.2.30 on 2026-08-31 15:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0003_alter_branch_organization_and_code'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('promotions', '0002_create_cache_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='LotteryDraw',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_deleted', models.BooleanField(default=False)),
                ('source', models.CharField(choices=[('points', 'Points redemption'), ('direct', 'Spend threshold')], max_length=10)),
                ('points_spent', models.PositiveIntegerField(default=0)),
                ('request_id', models.CharField(max_length=64, unique=True)),
                ('prize_name_snapshot', models.CharField(blank=True, max_length=120)),
                ('reward_type_snapshot', models.CharField(blank=True, max_length=16)),
                ('weight_snapshot', models.PositiveIntegerField(default=0)),
                ('total_weight_snapshot', models.PositiveIntegerField(default=0)),
                ('points_refunded', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('won', 'Won a prize'), ('refund', 'Points refund only')], max_length=10)),
                ('drawn_at', models.DateTimeField(auto_now_add=True)),
                ('local_date', models.DateField(help_text='Business day of the draw, for daily-stock counting.')),
                ('branch', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='promo_draws', to='branches.branch')),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='draws', to='promotions.campaign')),
            ],
            options={
                'ordering': ['-drawn_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='Milestone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points_threshold', models.PositiveIntegerField()),
                ('reward_type', models.CharField(choices=[('cash_voucher', 'Cash voucher'), ('drink', 'Drink'), ('dessert', 'Dessert'), ('side_dish', 'Side dish'), ('chef_special', "Chef's special"), ('points_refund', 'Points refund')], max_length=16)),
                ('reward_config', models.JSONField(blank=True, default=dict)),
                ('voucher_expires_after_days', models.PositiveIntegerField(default=45)),
                ('display_label', models.CharField(blank=True, max_length=120)),
                ('active', models.BooleanField(default=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='milestones', to='promotions.campaign')),
            ],
            options={
                'ordering': ['campaign', 'points_threshold'],
            },
        ),
        migrations.AddField(
            model_name='customer',
            name='draw_chances',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='customer',
            name='lifetime_points_earned',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='pointsledger',
            name='reason',
            field=models.CharField(choices=[('spend', 'Spend'), ('milestone', 'Milestone'), ('draw', 'Lottery draw'), ('draw_refund', 'Draw refund'), ('voucher', 'Voucher redeem'), ('expire', 'Expiry'), ('adjust', 'Manual adjustment')], max_length=16),
        ),
        migrations.CreateModel(
            name='Voucher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_deleted', models.BooleanField(default=False)),
                ('source', models.CharField(choices=[('lottery', 'Lottery win'), ('milestone', 'Milestone'), ('points_redeem', 'Points redemption')], max_length=16)),
                ('reward_type', models.CharField(choices=[('cash_voucher', 'Cash voucher'), ('drink', 'Drink'), ('dessert', 'Dessert'), ('side_dish', 'Side dish'), ('chef_special', "Chef's special"), ('points_refund', 'Points refund')], max_length=16)),
                ('config_snapshot', models.JSONField(blank=True, default=dict)),
                ('min_spend_yen', models.PositiveIntegerField(default=0)),
                ('requires_manual_approval', models.BooleanField(default=False)),
                ('redemption_code', models.CharField(max_length=16, unique=True)),
                ('redeem_request_id', models.CharField(blank=True, max_length=64)),
                ('issued_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('status', models.CharField(choices=[('active', 'Active'), ('redeemed', 'Redeemed'), ('expired', 'Expired'), ('void', 'Void')], default='active', max_length=10)),
                ('redeemed_at', models.DateTimeField(blank=True, null=True)),
                ('redeemed_spend_yen', models.PositiveIntegerField(blank=True, null=True)),
                ('void_reason', models.CharField(blank=True, max_length=255)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('branch', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='promo_vouchers', to='branches.branch')),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vouchers', to='promotions.campaign')),
                ('customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vouchers', to='promotions.customer')),
                ('redeemed_branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='branches.branch')),
                ('redeemed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('source_draw', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vouchers', to='promotions.lotterydraw')),
                ('source_milestone', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vouchers', to='promotions.milestone')),
            ],
            options={
                'ordering': ['-issued_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='Prize',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('weight', models.PositiveIntegerField(help_text='Relative odds; 0 disables without deleting.')),
                ('reward_type', models.CharField(choices=[('cash_voucher', 'Cash voucher'), ('drink', 'Drink'), ('dessert', 'Dessert'), ('side_dish', 'Side dish'), ('chef_special', "Chef's special"), ('points_refund', 'Points refund')], max_length=16)),
                ('reward_config', models.JSONField(blank=True, default=dict)),
                ('total_stock', models.PositiveIntegerField(blank=True, null=True)),
                ('remaining_stock', models.PositiveIntegerField(blank=True, null=True)),
                ('daily_stock', models.PositiveIntegerField(blank=True, null=True)),
                ('voucher_expires_after_days', models.PositiveIntegerField(default=30)),
                ('voucher_min_spend_yen', models.PositiveIntegerField(default=0)),
                ('requires_manual_approval', models.BooleanField(default=False)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prizes', to='promotions.campaign')),
            ],
            options={
                'ordering': ['campaign', 'display_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='MilestoneClaim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lifetime_points_at_claim', models.PositiveIntegerField()),
                ('claimed_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='milestone_claims', to='promotions.customer')),
                ('milestone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='claims', to='promotions.milestone')),
                ('voucher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='promotions.voucher')),
            ],
            options={
                'ordering': ['-claimed_at'],
            },
        ),
        migrations.AddField(
            model_name='lotterydraw',
            name='customer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='draws', to='promotions.customer'),
        ),
        migrations.AddField(
            model_name='lotterydraw',
            name='prize',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='draws', to='promotions.prize'),
        ),
        migrations.AddField(
            model_name='lotterydraw',
            name='spend_verification',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='draws', to='promotions.spendverification'),
        ),
        migrations.AddIndex(
            model_name='voucher',
            index=models.Index(fields=['customer', 'status'], name='promotions__custome_c8ae2a_idx'),
        ),
        migrations.AddIndex(
            model_name='voucher',
            index=models.Index(fields=['redemption_code'], name='promotions__redempt_83f472_idx'),
        ),
        migrations.AddConstraint(
            model_name='milestoneclaim',
            constraint=models.UniqueConstraint(fields=('customer', 'milestone'), name='unique_promo_milestone_claim'),
        ),
        migrations.AddConstraint(
            model_name='milestone',
            constraint=models.UniqueConstraint(fields=('campaign', 'points_threshold'), name='unique_promo_milestone_threshold'),
        ),
        migrations.AddIndex(
            model_name='lotterydraw',
            index=models.Index(fields=['prize', 'branch', 'local_date'], name='promotions__prize_i_d1b182_idx'),
        ),
        migrations.AddIndex(
            model_name='lotterydraw',
            index=models.Index(fields=['customer', 'local_date'], name='promotions__custome_e291e2_idx'),
        ),
    ]
