# Generated by Django 4.2.30 on 2026-08-31 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promotions', '0003_lotterydraw_milestone_customer_draw_chances_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='max_draws_per_customer_per_day',
            field=models.PositiveIntegerField(blank=True, default=10, null=True),
        ),
    ]
