# Generated by Django 4.2.30 on 2026-09-01 00:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0003_alter_branch_organization_and_code'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('organizations', '0002_backfill_default_organization'),
        ('promotions', '0004_alter_campaign_max_draws_per_customer_per_day'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='registered_ip',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='StaffPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('can_verify_spend', models.BooleanField(default=True)),
                ('can_redeem_voucher', models.BooleanField(default=True)),
                ('note', models.CharField(blank=True, max_length=255)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='promo_permission', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RiskEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('off_hours_verification', 'Off-hours spend confirmation'), ('staff_rapid_verifications', 'Staff confirmed many spends fast'), ('amount_equals_threshold', 'Amount exactly a voucher threshold'), ('customer_multi_branch', 'Same customer across many branches'), ('device_multi_register', 'One device registered many phones'), ('customer_rapid_draws', 'Same customer drew many times fast'), ('high_value_prize_streak', 'Concentrated high-value wins'), ('voided_after_redemption', 'Spend voided after value was used')], max_length=32)),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='medium', max_length=8)),
                ('evidence', models.JSONField(blank=True, default=dict)),
                ('source_ref', models.CharField(blank=True, max_length=64)),
                ('dedupe_key', models.CharField(max_length=128, unique=True)),
                ('status', models.CharField(choices=[('open', 'Open'), ('reviewed', 'Reviewed — legitimate'), ('confirmed', 'Reviewed — confirmed issue'), ('dismissed', 'Dismissed')], default='open', max_length=10)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('review_note', models.CharField(blank=True, max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='promo_risk_events', to='branches.branch')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='risk_events', to='promotions.customer')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promo_risk_events', to='organizations.organization')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('staff_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['organization', 'status'], name='promotions__organiz_357db7_idx'), models.Index(fields=['organization', 'event_type'], name='promotions__organiz_73d9f8_idx')],
            },
        ),
    ]
