# Generated by Django 4.2.30 on 2026-09-01 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promotions', '0005_customer_registered_ip_staffpermission_riskevent'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='pin_hash',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
        migrations.AlterField(
            model_name='riskevent',
            name='event_type',
            field=models.CharField(choices=[('off_hours_verification', 'Off-hours spend confirmation'), ('staff_rapid_verifications', 'Staff confirmed many spends fast'), ('amount_equals_threshold', 'Amount exactly a voucher threshold'), ('customer_multi_branch', 'Same customer across many branches'), ('device_multi_register', 'One device registered many phones'), ('customer_rapid_draws', 'Same customer drew many times fast'), ('high_value_prize_streak', 'Concentrated high-value wins'), ('voided_after_redemption', 'Spend voided after value was used'), ('pin_recovery_lockout', 'Card PIN recovery locked after repeated failures')], max_length=32),
        ),
    ]
