# Generated by Django 4.2.30 on 2026-09-03 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promotions', '0006_customer_pin_hash_alter_riskevent_event_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='spendverification',
            name='request_id',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
    ]
