# Generated by Django 4.2.30 on 2026-09-05 14:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('promotions', '0007_spendverification_request_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='active_date_from',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='campaign',
            name='active_date_to',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='campaign',
            name='active_weekdays',
            field=models.CharField(default='1234567', max_length=7),
        ),
        migrations.AddField(
            model_name='campaign',
            name='checkin_reward_config',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='campaign',
            name='checkin_reward_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='campaign',
            name='checkin_reward_expires_after_days',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='campaign',
            name='checkin_reward_type',
            field=models.CharField(blank=True, default='', max_length=16),
        ),
        migrations.AddField(
            model_name='campaign',
            name='priority',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='checkinrecord',
            name='reward_voucher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='promotions.voucher'),
        ),
        migrations.AlterField(
            model_name='voucher',
            name='source',
            field=models.CharField(choices=[('lottery', 'Lottery win'), ('milestone', 'Milestone'), ('points_redeem', 'Points redemption'), ('checkin', 'Daily check-in')], max_length=16),
        ),
    ]
