# Generated by Django 4.2.30 on 2026-09-05 16:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('promotions', '0008_campaign_active_date_from_campaign_active_date_to_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CheckinMilestone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checkin_threshold', models.PositiveIntegerField(help_text='Total check-ins that unlocks this reward.')),
                ('reward_type', models.CharField(choices=[('cash_voucher', 'Cash voucher'), ('drink', 'Drink'), ('dessert', 'Dessert'), ('side_dish', 'Side dish'), ('chef_special', "Chef's special"), ('points_refund', 'Points refund')], max_length=16)),
                ('reward_config', models.JSONField(blank=True, default=dict)),
                ('voucher_expires_after_days', models.PositiveIntegerField(default=7)),
                ('display_label', models.CharField(blank=True, max_length=120)),
                ('active', models.BooleanField(default=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checkin_milestones', to='promotions.campaign')),
            ],
            options={
                'ordering': ['campaign', 'checkin_threshold'],
            },
        ),
        migrations.CreateModel(
            name='CheckinMilestoneClaim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checkins_at_claim', models.PositiveIntegerField()),
                ('claimed_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checkin_milestone_claims', to='promotions.customer')),
                ('milestone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='claims', to='promotions.checkinmilestone')),
                ('voucher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='promotions.voucher')),
            ],
            options={
                'ordering': ['-claimed_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='checkinmilestoneclaim',
            constraint=models.UniqueConstraint(fields=('customer', 'milestone'), name='unique_promo_checkin_milestone_claim'),
        ),
        migrations.AddConstraint(
            model_name='checkinmilestone',
            constraint=models.UniqueConstraint(fields=('campaign', 'checkin_threshold'), name='unique_promo_checkin_milestone_threshold'),
        ),
    ]
