# Generated by Django 4.2.30 on 2026-09-07 12:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('promotions', '0009_checkinmilestone_checkinmilestoneclaim_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RedemptionOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('points_cost', models.PositiveIntegerField()),
                ('reward_type', models.CharField(choices=[('cash_voucher', 'Cash voucher'), ('drink', 'Drink'), ('dessert', 'Dessert'), ('side_dish', 'Side dish'), ('chef_special', "Chef's special"), ('points_refund', 'Points refund')], max_length=16)),
                ('reward_config', models.JSONField(blank=True, default=dict)),
                ('voucher_expires_after_days', models.PositiveIntegerField(default=45)),
                ('voucher_min_spend_yen', models.PositiveIntegerField(default=0)),
                ('total_stock', models.PositiveIntegerField(blank=True, null=True)),
                ('remaining_stock', models.PositiveIntegerField(blank=True, null=True)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='redemption_options', to='promotions.campaign')),
            ],
            options={
                'ordering': ['campaign', 'display_order', 'id'],
            },
        ),
    ]
