# Generated by Django 4.2.30 on 2026-09-07 15:45

import secrets

from django.db import migrations, models


def fill_checkin_secrets(apps, schema_editor):
    Campaign = apps.get_model('promotions', 'Campaign')
    for pk in Campaign.objects.filter(checkin_secret='').values_list('pk', flat=True):
        Campaign.objects.filter(pk=pk).update(checkin_secret=secrets.token_hex(32))


class Migration(migrations.Migration):

    dependencies = [
        ('promotions', '0010_redemptionoption'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='checkin_requires_live_qr',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='campaign',
            name='checkin_secret',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.RunPython(fill_checkin_secrets, migrations.RunPython.noop),
    ]
