# Generated by Django 4.2.30 on 2026-08-17 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffmember',
            name='employment_type',
            field=models.CharField(choices=[('regular_monthly', 'Regular/monthly salaried'), ('hourly', 'Hourly'), ('temporary', 'Temporary')], default='regular_monthly', help_text='regular_monthly employees only have hours tracked this phase — wages are only calculated for hourly/temporary staff.', max_length=20),
        ),
        migrations.AddField(
            model_name='staffmember',
            name='hire_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='staffmember',
            name='leave_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='staffmember',
            name='note',
            field=models.TextField(blank=True),
        ),
    ]
