# Generated by Django 4.2.30 on 2026-08-19 14:05

from django.db import migrations, models


def infer_work_area(apps, schema_editor):
    StaffMember = apps.get_model('staff', 'StaffMember')
    kitchen_terms = ('厨房', 'キッチン', '調理', '厨师', '廚房', 'kitchen', 'cook', 'chef')
    for employee in StaffMember.objects.all().iterator():
        role = (employee.role or '').lower()
        employee.work_area = 'kitchen' if any(term in role for term in kitchen_terms) else 'hall'
        employee.save(update_fields=['work_area'])


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0003_stafftransfer'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffmember',
            name='work_area',
            field=models.CharField(choices=[('kitchen', 'Kitchen'), ('hall', 'Hall')], default='hall', max_length=10),
        ),
        migrations.RunPython(infer_work_area, migrations.RunPython.noop),
    ]
