# Generated by Django 4.2.30 on 2026-08-16 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.SlugField(primary_key=True, serialize=False)),
                ('name_zh', models.CharField(max_length=100)),
                ('name_ja', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
