# Generated by Django 4.2.30 on 2026-08-18 12:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0001_initial'),
        ('branches', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='code',
            field=models.SlugField(blank=True, help_text='Unique within the Organization; may repeat across different Organizations.', null=True),
        ),
        migrations.AddField(
            model_name='branch',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='branches', to='organizations.organization'),
        ),
        migrations.AddConstraint(
            model_name='branch',
            constraint=models.UniqueConstraint(fields=('organization', 'code'), name='unique_branch_code_per_organization'),
        ),
    ]
